config/routes.rb
LicenseManagement::Application.routes.draw do
  match '/dashboard' => 'static_pages#dashboard', as: :dashboard
  match '/login' => 'sessions#new', as: :login
  match '/logout' => 'sessions#destroy', as: :logout

  match '/reports/thirty_sixty_ninety' => 'reports#thirty_sixty_ninety', as: :reports_thirty_sixty_ninety
  match '/reports/month_expire_by_type' => 'reports#month_expire_by_type', as: :reports_month_expire_by_type
  match '/reports/license_type' => 'reports#license_type', as: :reports_license_type
  match '/reports/funding_source' => 'reports#funding_source', as: :reports_funding_source

  resources :events
  resources :delivery_types
  resources :funding_sources
  resources :groups
  resources :installation_types
  resources :license_statuses
  resources :license_types
  resources :platforms
  resources :product_versions
  resources :purchase_orders do
    resources :licenses
  end
  resources :regions
  resources :server_types
  resources :sessions, only: [:new, :create, :destroy]
 
  match '/proposal' => 'licenses#proposal'
  match '/angular' => 'static_pages#angular'

  root :to => 'static_pages#dashboard'
end

app/models/agreement.rb
class Agreement < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/delivery_type.rb
class DeliveryType < ActiveRecord::Base
  attr_accessible :name
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :description, :priority
end

app/models/funding_source.rb
class FundingSource < ActiveRecord::Base
  attr_accessible :name

  has_many :purchase_orders

  validates_presence_of :name

  def to_s
    self.name
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
end

app/models/installation_type.rb
class InstallationType < ActiveRecord::Base
  attr_accessible :name
end

app/models/license.rb
class License < ActiveRecord::Base
  attr_accessible :license_type_id, :end_date, :start_date, :quantity, :license_status_id, :purchase_order_id, :net_suite_account_id

  belongs_to :purchase_order
  belongs_to :license_status
  belongs_to :license_type
  has_many :notes, as: :noteable

  validates_presence_of :quantity
  validates_presence_of :purchase_order_id
  validates_presence_of :license_type_id
end

app/models/license_history.rb
class LicenseHistory < ActiveRecord::Base
  attr_accessible :created_by, :current_agreement_id, :current_license_status_id, :current_license_type_id, :event_id, :license_id, :notes, :previous_agreement_id, :previous_license_status_id, :previous_license_type_id, :reason_id

  validates_presence_of :license_id
end

app/models/license_status.rb
class LicenseStatus < ActiveRecord::Base
  attr_accessible :name

  has_many :licenses

  def to_s
    self.name
  end
end

app/models/license_type.rb
class LicenseType < ActiveRecord::Base
  attr_accessible :name

  has_many :licenses

  validates_presence_of :name

  def to_s
    self.name
  end
end

app/models/net_suite_account.rb
class NetSuiteAccount < ActiveRecord::Base
  attr_accessible :account_id, :name, :parent_name

  validates_presence_of :account_id
  validates_presence_of :name
  validates_presence_of :parent_name
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :description

  belongs_to :noteable, polymorphic: true
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  attr_accessible :name
end

app/models/product_version.rb
class ProductVersion < ActiveRecord::Base
  attr_accessible :name

  def to_s
    self.name
  end
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  attr_accessible :apm, :created_by, :deleted, :sts, :invoice_number, :modified_by, :net_suite_account_id, :purchase_order_date, :number, :region_id, :sale_number, :funding_source_id, :quantity

  validates_presence_of :number

  has_many :licenses
  has_many :notes, as: :noteable
  belongs_to :funding_source
  belongs_to :region

  def to_s
    self.number
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :name

  has_many :purchase_orders

  validates_presence_of :name

  def to_s
    self.name
  end
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :created_by, :deleted, :modified_by, :number
end

app/models/server_type.rb
class ServerType < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    respond_to do |format|
      format.html
      format.js { Event.all.to_json }
    end
  end

  def new
    @license_status = LicenseEvent.new
  end

  def create
    @license_status = LicenseEvent.new(params[:license_status])

    if @license_status.save
      redirect_to @license_status, notice: 'Successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @license_status = LicenseEvent.find(params[:id])
  end

  def show
    @license_status = LicenseEvent.find(params[:id])
  end

  def update
    @license_status = LicenseEvent.find(params[:id])

    if @license_status.update_attributes(params[:license_status])
      redirect_to @license_status, notice: 'Successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @license_status = LicenseEvent.find(params[:id])
    @license_status.destroy
  end
end

app/controllers/funding_sources_controller.rb
class FundingSourcesController < ApplicationController
  def index
    @q = FundingSource.search(params[:q])
    @funding_sources = @q.result(distinct: true).paginate(per_page: 20, page: params[:page])
  end

  def new
    @funding_source = FundingSource.new
  end

  def create
    @funding_source = FundingSource.new(params[:funding_source])

    if @funding_source.save
      redirect_to @funding_source, notice: 'Successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @funding_source = FundingSource.find(params[:id])
  end

  def show
    @funding_source = FundingSource.find(params[:id])
  end

  def update
    @funding_source = FundingSource.find(params[:id])

    if @funding_source.update_attributes(params[:funding_source])
      redirect_to @funding_source, notice: 'Successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @funding_source = FundingSource.find(params[:id])
    @funding_source.destroy
    redirect_to @funding_source, notice: 'Successfully deleted.'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @q = Group.search(params[:q])
    @groups = @q.result(distinct: true).paginate(per_page: 20, page: params[:page])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])

    if @group.save
      redirect_to @group, notice: 'Successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def show
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update_attributes(params[:group])
      redirect_to @group, notice: 'Successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to @group, notice: 'Successfully deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    return page_title.empty? ? "License Management" : page_title
  end
end

app/views/funding_sources/_form.html.erb
<%= form_for @funding_source, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'layouts/error_messages', target: @funding_source %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                funding_sources_path, :class => 'btn' %>
  </div>
<% end %>

app/views/funding_sources/edit.html.erb
<%- model_class = FundingSource -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/funding_sources/index.html.erb
<%- model_class = FundingSource -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<%= will_paginate(@funding_sources) %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_funding_source_path,
            :class => 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @funding_sources.each do |funding_source| %>
      <tr>
        <td><%= link_to funding_source.name, funding_source_path(funding_source) %></td>
        <td><%=l funding_source.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_funding_source_path(funding_source), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      funding_source_path(funding_source),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/funding_sources/new.html.erb
<%- model_class = FundingSource -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/funding_sources/show.html.erb
<%- model_class = FundingSource -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @funding_source.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              funding_sources_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_funding_source_path(@funding_source), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              funding_source_path(@funding_source),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>