config/routes.rb
LicenseManagement::Application.routes.draw do
  match '/dashboard' => 'static_pages#dashboard', as: :dashboard
  match '/login' => 'sessions#new', as: :login
  match '/logout' => 'sessions#destroy', as: :logout

  match '/reports/thirty_sixty_ninety' => 'reports#thirty_sixty_ninety', as: :reports_thirty_sixty_ninety
  match '/reports/month_expire_by_type' => 'reports#month_expire_by_type', as: :reports_month_expire_by_type
  match '/reports/license_type' => 'reports#license_type', as: :reports_license_type
  match '/reports/funding_source' => 'reports#funding_source', as: :reports_funding_source

  resources :events
  resources :delivery_types
  resources :funding_sources
  resources :groups
  resources :installation_types
  resources :license_statuses
  resources :license_types
  resources :platforms
  resources :product_versions
  resources :purchase_orders do
    resources :licenses
  end
  resources :regions
  resources :server_types
  resources :sessions, only: [:new, :create, :destroy]
 
  match '/proposal' => 'licenses#proposal'
  match '/angular' => 'static_pages#angular'

  root :to => 'static_pages#dashboard'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def thirty_sixty_ninety 
    @start = Time.now.to_date
    @end = @start + 3.months

    @licenses = License.select('SUM(licenses.quantity) AS count_all, STRFTIME("%Y-%m", licenses.end_date) AS date_expiring')
      .joins('INNER JOIN purchase_orders ON licenses.purchase_order_id = purchase_orders.id')
      .where('licenses.end_date BETWEEN ? AND ?', @start, @end)

    @licenses =  @licenses.group('STRFTIME("%Y-%m", licenses.end_date)') if Rails.env.development?
    @licenses =  @licenses.group("DATE_TRUNC('month', licenses.end_date)") if Rails.env.production?

    @categories = Array.new
    @licenses_total = Array.new

    months = months_between(@start, @end)

    months.each do |month|
      @categories << month

      licenses_count = @licenses.find { |v| v.date_expiring == month }
      @licenses_total << (licenses_count.present? ? licenses_count.count_all : 0)
    end
  end

  def month_expire_by_type
    now = Time.now
    @month = Date.strptime(params[:month], "%Y-%m") if params[:month].present?
    @month ||= now.beginning_of_month.to_date

    @licenses = License.select('SUM(licenses.quantity) AS count_all, license_types.name')
    .joins('INNER JOIN license_types ON licenses.license_type_id = license_types.id')
    .where('STRFTIME("%Y-%m", licenses.end_date) = ?', @month.strftime('%Y-%m'))
    .group('license_types.name')

    license_types = LicenseType.all

    @categories = Array.new
    @licenses_total = Array.new

    license_types.each do |license_type|
      @categories << license_type.name

      licenses_count = @licenses.find { |l| l.name == license_type.name }
      @licenses_total << (licenses_count.present? ? licenses_count.count_all : 0)
    end
  end

  def license_type
    @licenses = License.select('SUM(licenses.quantity) AS count_all, license_types.name')
    .joins('INNER JOIN license_types ON licenses.license_type_id = license_types.id')
    .group('license_types.name')

    license_types = LicenseType.all
    license_total = License.sum('quantity')

    @categories = Array.new
    @licenses_total = Array.new
    @license_data = Array.new

    license_types.each do |license_type|
      @categories << license_type.name

      licenses_count = @licenses.find { |l| l.name == license_type.name }
      license_count = (licenses_count.present? ? licenses_count.count_all : 0)
      @licenses_total << license_count
      license_percent = get_percentage(license_count.to_f, license_total.to_f)

      @license_data << "'" + license_type.name + "', " + license_percent
    end 

    @data = @license_data.collect{ |l| "[#{l}]" }.join(",")
  end

  def funding_source
    @purchase_orders = PurchaseOrder.select('SUM(purchase_orders.quantity) AS count_all, funding_sources.name')
    .joins('INNER JOIN funding_sources ON purchase_orders.funding_source_id = funding_sources.id')
    .group('funding_sources.name')

    funding_source_types = FundingSource.all
    purchase_order_total = PurchaseOrder.sum('quantity')

    @categories = Array.new
    @purchase_orders_total = Array.new
    @purchase_order_data = Array.new

    funding_source_types.each do |funding_source|
      @categories << funding_source.name

      purchase_orders_count = @purchase_orders.find { |po| po.name == funding_source.name }
      purchase_order_count = (purchase_orders_count.present? ? purchase_orders_count.count_all : 0)
      @purchase_orders_total << purchase_order_count
      purchase_order_percent = get_percentage(purchase_order_count.to_f, purchase_order_total.to_f)

      @purchase_order_data << "'" + funding_source.name + "', " + purchase_order_percent
    end 
    logger.info "PO DATA " + @purchase_order_data.inspect

    @data = @purchase_order_data.collect{ |l| "[#{l}]" }.join(",")
  end

  def get_percentage(count, total)
    return "0.00" if count == 0
    sprintf("%.2f", ((count.to_f / total.to_f) * 100))
  end

  def months_between(start_month, end_month)
    months = []
    ptr = start_month
    while ptr <= end_month do
      months << "#{ptr.year}-#{sprintf('%02d', ptr.month)}"
      ptr = ptr >> 1
    end
    months
  end
end

app/views/reports/funding_source.html.erb
<script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>

<script type="text/javascript">
$(function () {
    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'report_container',
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'License share by Funding Source'
            },
            tooltip: {
              pointFormat: '{series.name}: <b>{point.percentage}%</b>',
              percentageDecimals: 1
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        formatter: function() {
                            return '<b>'+ this.point.name +'</b>: '+ this.percentage +' %';
                        }
                    }
                }
            },
            series: [{
                type: 'pie',
                name: 'Funding Source',
                data: [
                  <%= raw @data %>
                  ]
            }]
        });
    });
    
});
</script>

<div id="report_container" style="min-width: 400px; height: 400px; margin: 0 auto;"></div>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Licenses</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each.with_index do |date, index| %>
      <tr>
        <td><%= @categories[index] %></td>
        <td><%= @purchase_orders_total[index] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/license_type.html.erb
<script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>

<script type="text/javascript">
$(function () {
    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'report_container',
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'Browser market shares at a specific website, 2010'
            },
            tooltip: {
              pointFormat: '{series.name}: <b>{point.percentage}%</b>',
              percentageDecimals: 1
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        formatter: function() {
                            return '<b>'+ this.point.name +'</b>: '+ this.percentage +' %';
                        }
                    }
                }
            },
            series: [{
                type: 'pie',
                name: 'Browser share',
                data: [
                  <%= raw @data %>
                  ]
            }]
        });
    });
    
});
</script>

<div id="report_container" style="min-width: 400px; height: 400px; margin: 0 auto;"></div>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Licenses</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each.with_index do |date, index| %>
      <tr>
        <td><%= @categories[index] %></td>
        <td><%= @licenses_total[index] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/month_expire_by_type.html.erb
<script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>

<script type="text/javascript">
$(function () {
    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
              renderTo: 'report_container',
              type: 'column',
              marginBottom: 120
            },
            title: {
              text: 'Monthly Expires By License Type',
              x: -20
            },
            subtitle: {
              text: 'Expiring licenses',
              x: -20
            },
            xAxis: {
              categories: <%= raw @categories.map { |c| "#{c}" } %>,
              labels: {
                rotation: -45,
                align: 'right',
                style: {
                  fontSize: '13px',
                  fontFamily: 'Verdana, sans-serif'
                }
              }
            },
            yAxis: {
              min: 0,
              allowDecimals: false,
              title: {
                text: 'Total'
              },
              plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
              }]
            },
            tooltip: {
              formatter: function() {
                return '<b>'+ this.series.name +'</b><br/>'+
                this.x +': '+ this.y;
              }
            },
            series: [{
              name: 'Licenses',
              data: <%= raw @licenses_total.map { |l| l } %>
            }]
        });
    });
});
</script>

<div id="report_container" style="min-width: 400px; height: 400px; margin: 0 auto;"></div>

<%= form_tag "", method: :get do %>
  <p><%= label_tag :month %><%= text_field_tag :month, @month.strftime("%Y-%m") %></p>
  <p><%= submit_tag :View, name: nil %></p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Licenses</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each.with_index do |date, index| %>
      <tr>
        <td><%= @categories[index] %></td>
        <td><%= @licenses_total[index] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/thirty_sixty_ninety.html.erb
<script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>

<script type="text/javascript">
$(function () {
    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
              renderTo: 'report_container',
              type: 'column',
              marginBottom: 120
            },
            title: {
              text: '30, 60, 90',
              x: -20
            },
            subtitle: {
              text: 'Licenses Up For Renewal',
              x: -20
            },
            xAxis: {
              categories: <%= raw @categories.map { |c| "#{c}" } %>,
              labels: {
                rotation: -45,
                align: 'right',
                style: {
                  fontSize: '13px',
                  fontFamily: 'Verdana, sans-serif'
                }
              }
            },
            yAxis: {
              min: 0,
              allowDecimals: false,
              title: {
                text: 'Total'
              },
              plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
              }]
            },
            tooltip: {
              formatter: function() {
                return '<b>'+ this.series.name +'</b><br/>'+
                this.x +': '+ this.y;
              }
            },
            series: [{
              name: 'Licenses',
              data: <%= raw @licenses_total.map { |l| l } %>
            }]
        });
    });
});
</script>

<div id="report_container" style="min-width: 400px; height: 400px; margin: 0 auto;"></div>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Licenses</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each.with_index do |date, index| %>
      <tr>
        <td><%= link_to @categories[index], reports_month_expire_by_type_path(month: @categories[index]) %></td>
        <td><%= @licenses_total[index] %></td>
      </tr>
    <% end %>
  </tbody>
</table>